# Generated by Django 3.1 on 2020-08-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlistitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.auctionlisting'),
        ),
    ]
